name = "sequential"
[[layers]]
module = "keras.layers"
class_name = "InputLayer"

[layers.config]
batch_input_shape = [ "None", 256, 256, 1,]
dtype = "float32"
sparse = false
ragged = false
name = "input_1"
[[layers]]
module = "keras.layers"
class_name = "Conv2D"

[layers.config]
name = "conv2d"
trainable = true
dtype = "float32"
filters = 3
kernel_size = [ 3, 3,]
strides = [ 1, 1,]
padding = "same"
data_format = "channels_last"
dilation_rate = [ 1, 1,]
groups = 1
activation = "linear"
use_bias = true
[layers.build_config]
input_shape = [ "None", 256, 256, 1,]
[layers.config.kernel_initializer]
module = "keras.initializers"
class_name = "GlorotUniform"
[layers.config.bias_initializer]
module = "keras.initializers"
class_name = "Zeros"
[[layers]]
module = "keras.layers"
class_name = "ReLU"

[layers.config]
name = "re_lu"
trainable = true
dtype = "float32"
negative_slope = 0.0
threshold = 0.0
[layers.build_config]
input_shape = [ "None", 256, 256, 3,]
[[layers]]
module = "keras.layers"
class_name = "MaxPooling2D"

[layers.config]
name = "max_pooling2d"
trainable = true
dtype = "float32"
pool_size = [ 4, 4,]
padding = "valid"
strides = [ 4, 4,]
data_format = "channels_last"
[layers.build_config]
input_shape = [ "None", 256, 256, 3,]
[[layers]]
module = "keras.layers"
class_name = "Conv2D"

[layers.config]
name = "conv2d_1"
trainable = true
dtype = "float32"
filters = 3
kernel_size = [ 3, 3,]
strides = [ 1, 1,]
padding = "same"
data_format = "channels_last"
dilation_rate = [ 1, 1,]
groups = 1
activation = "linear"
use_bias = true
[layers.build_config]
input_shape = [ "None", 64, 64, 3,]
[layers.config.kernel_initializer]
module = "keras.initializers"
class_name = "GlorotUniform"
[layers.config.bias_initializer]
module = "keras.initializers"
class_name = "Zeros"
[[layers]]
module = "keras.layers"
class_name = "ReLU"

[layers.config]
name = "re_lu_1"
trainable = true
dtype = "float32"
negative_slope = 0.0
threshold = 0.0
[layers.build_config]
input_shape = [ "None", 64, 64, 3,]
[[layers]]
module = "keras.layers"
class_name = "MaxPooling2D"

[layers.config]
name = "max_pooling2d_1"
trainable = true
dtype = "float32"
pool_size = [ 4, 4,]
padding = "valid"
strides = [ 4, 4,]
data_format = "channels_last"
[layers.build_config]
input_shape = [ "None", 64, 64, 3,]
[[layers]]
module = "keras.layers"
class_name = "Conv2D"

[layers.config]
name = "conv2d_2"
trainable = true
dtype = "float32"
filters = 3
kernel_size = [ 3, 3,]
strides = [ 1, 1,]
padding = "same"
data_format = "channels_last"
dilation_rate = [ 1, 1,]
groups = 1
activation = "linear"
use_bias = true
[layers.build_config]
input_shape = [ "None", 16, 16, 3,]
[layers.config.kernel_initializer]
module = "keras.initializers"
class_name = "GlorotUniform"
[layers.config.bias_initializer]
module = "keras.initializers"
class_name = "Zeros"
[[layers]]
module = "keras.layers"
class_name = "ReLU"

[layers.config]
name = "re_lu_2"
trainable = true
dtype = "float32"
negative_slope = 0.0
threshold = 0.0
[layers.build_config]
input_shape = [ "None", 16, 16, 3,]
[[layers]]
module = "keras.layers"
class_name = "MaxPooling2D"

[layers.config]
name = "max_pooling2d_2"
trainable = true
dtype = "float32"
pool_size = [ 4, 4,]
padding = "valid"
strides = [ 4, 4,]
data_format = "channels_last"
[layers.build_config]
input_shape = [ "None", 16, 16, 3,]
[[layers]]
module = "keras.layers"
class_name = "Flatten"

[layers.config]
name = "flatten"
trainable = true
dtype = "float32"
data_format = "channels_last"
[layers.build_config]
input_shape = [ "None", 4, 4, 3,]
[[layers]]
module = "keras.layers"
class_name = "Dropout"

[layers.config]
name = "dropout"
trainable = true
dtype = "float32"
rate = 0.5
[layers.build_config]
input_shape = [ "None", 48,]
[[layers]]
module = "keras.layers"
class_name = "Dense"

[layers.config]
name = "dense"
trainable = true
dtype = "float32"
units = 128
activation = "linear"
use_bias = true
[layers.build_config]
input_shape = [ "None", 48,]
[layers.config.kernel_initializer]
module = "keras.initializers"
class_name = "GlorotUniform"
[layers.config.bias_initializer]
module = "keras.initializers"
class_name = "Zeros"
[[layers]]
module = "keras.layers"
class_name = "ReLU"

[layers.config]
name = "re_lu_3"
trainable = true
dtype = "float32"
negative_slope = 0.0
threshold = 0.0
[layers.build_config]
input_shape = [ "None", 128,]
[[layers]]
module = "keras.layers"
class_name = "Dropout"

[layers.config]
name = "dropout_1"
trainable = true
dtype = "float32"
rate = 0.5
[layers.build_config]
input_shape = [ "None", 128,]
[[layers]]
module = "keras.layers"
class_name = "Dense"

[layers.config]
name = "dense_1"
trainable = true
dtype = "float32"
units = 24
activation = "linear"
use_bias = true
[layers.build_config]
input_shape = [ "None", 128,]
[layers.config.kernel_initializer]
module = "keras.initializers"
class_name = "GlorotUniform"
[layers.config.bias_initializer]
module = "keras.initializers"
class_name = "Zeros"
[[layers]]
module = "keras.layers"
class_name = "ReLU"

[layers.config]
name = "re_lu_4"
trainable = true
dtype = "float32"
negative_slope = 0.0
threshold = 0.0
[layers.build_config]
input_shape = [ "None", 24,]
[[layers]]
module = "keras.layers"
class_name = "Dropout"

[layers.config]
name = "dropout_2"
trainable = true
dtype = "float32"
rate = 0.2
[layers.build_config]
input_shape = [ "None", 24,]
[[layers]]
module = "keras.layers"
class_name = "Dense"

[layers.config]
name = "dense_2"
trainable = true
dtype = "float32"
units = 128
activation = "linear"
use_bias = true
[layers.build_config]
input_shape = [ "None", 24,]
[layers.config.kernel_initializer]
module = "keras.initializers"
class_name = "GlorotUniform"
[layers.config.bias_initializer]
module = "keras.initializers"
class_name = "Zeros"
